routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/jasa-restorasi', 'HomeController@listJasa')->name('list-jasa');
Route::get('/jasa/{jasa_id}', 'HomeController@detailJasa')->name('detail-jasa');
Route::get('/reservasi-jasa/{jasa_id}', 'HomeController@reservasiJasa')->name('reservasi-jasa');
Route::post('/reservasi-jasa/{jasa_id}', 'HomeController@storeReservasiJasa')->name('reservasi-jasa');

Route::get('/suku-cadang', 'HomeController@listSukuCadang')->name('list-suku-cadang');
Route::get('/suku-cadang/{suku_cadang_id}', 'HomeController@detailSukuCadang')->name('detail-suku-cadang');
Route::get('/booking/{suku_cadang_id}', 'HomeController@bookingSukuCadang')->name('booking-suku-cadang');
Route::post('/booking/{suku_cadang_id}', 'HomeController@storeBookingSukuCadang')->name('booking-suku-cadang');

Route::get('/daftar-keluhan-mobil', 'HomeController@listKeluhan')->name('list-keluhan');
Route::get('/daftar-keluhan-mobil/{keluhan_id}/{slug}', 'HomeController@detailKeluhan')->name('detail-keluhan');

Route::get('/bengkel/{bengkel_id}/{slug}', 'HomeController@detailBengkel')->name('detail-bengkel');
Route::get('/bengkel/', 'HomeController@listBengkel')->name('list-bengkel');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('users', 'UsersController');
    Route::resource('kota', 'KotaController');
    Route::resource('roles', 'RolesController');
    Route::resource('merk', 'MerkController');
    Route::resource('tipe', 'TipeController');
    Route::resource('seri', 'SeriController');
    Route::resource('bengkel', 'BengkelController');
    Route::resource('jasa', 'JasaController');

    Route::get('jasa-harga/{jasa_id}', 'JasaHargaController@create')->name('jasa-harga-form');
    Route::post('jasa-harga/{jasa_id}', 'JasaHargaController@store')->name('jasa-harga-store');
    Route::get('jasa-harga/{jasa_id}/{jasa_harga_id}', 'JasaHargaController@edit')->name('jasa-harga-edit');
    Route::put('jasa-harga/{jasa_id}/{jasa_harga_id}', 'JasaHargaController@update')->name('jasa-harga-update');
    Route::get('jasa-harga-hapus/{jasa_harga_id}', 'JasaHargaController@destroy')->name('jasa-harga-delete');

    Route::resource('suku-cadang', 'SukuCadangController');
    Route::resource('transaksi', 'TransaksiController');
    Route::resource('banner', 'BannerController');
    Route::resource('mekanik', 'MekanikController');
    Route::resource('keluhan', 'KeluhanController');
});

// call with ajax
Route::get('/ajax/get-tipe-by-merk/{merk_id}', 'TipeController@getByMerk')->name('ajax.get-tipe-by-merk');
Route::get('/ajax/get-seri-by-tipe/{tipe_id}', 'SeriController@getByTipe')->name('ajax.get-seri-by-tipe');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

Route::get('/foo', function () {
    Artisan::call('storage:link');
});

app/Models/Transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    protected $table = 'transaksi';

    public function bengkel()
    {
        return $this->belongsTo(Bengkel::class);
    }

    public function jasa()
    {
        return $this->belongsTo(Jasa::class);
    }

    public function paket()
    {
        return $this->belongsTo(JasaHarga::class);
    }

    public function sukucadang()
    {
        return $this->belongsTo(SukuCadang::class, 'suku_cadang_id', 'id');
    }

    public function getStatusPembayaranAttribute()
    {
        return $this->is_paid == 0 ? 'Belum Lunas' : 'Lunas';
    }
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bengkel;
use App\Models\Jasa;
use App\Models\Transaksi;
use App\Models\MasterKota;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id === 3){
            // cek user ini mempunyai bengkel apa saja
            $bengkelBelongCurrentUser = Bengkel::where('user_id', Auth::user()->id)->pluck('id')->toArray();

            $datas = Transaksi::whereIn('bengkel_id', $bengkelBelongCurrentUser)->get();
        }elseif (Auth::user()->role_id === 1){
            $datas = Transaksi::where('user_id', Auth::user()->id)->get();
        }else{
            $datas = Transaksi::all();
        }

        return view('admin.transaksi.transaksi', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit = false;
        $users = User::where('role_id', 3)->get(); // role admin transaksi
        $kota = MasterKota::orderBy('nama' , 'DESC')->get();
        return view('admin.transaksi.form', compact('edit', 'users', 'kota'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Transaksi();
        $data->nama = $request->name;
        $data->alamat = $request->alamat;
        $data->master_kota_id = $request->kota_id;
        $data->deskripsi = $request->deskripsi;
        $data->user_id = $request->user_id;
        $data->telepon = $request->telepon;
        $data->email = $request->email;

        if ($request->file('logo')) {
            $file = $request->file('logo')->store('logo', 'public');
            $data->logo = $file;
        }

        try{
            $data->save();
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('transaksi.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Transaksi::find($id);
        return view('admin.transaksi.detail', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $data = Transaksi::find($id);
        return view('admin.transaksi.form', compact('edit','data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Transaksi::find($id);
        $data->is_paid = $request->is_paid;

        try{
            $data->save();
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('transaksi.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            Transaksi::destroy($id);
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('transaksi.index');
    }
}

resources/views/admin/transaksi/detail.blade.php
@extends('layouts/admin')

@section('title', 'Transaksi')
@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/pickers/pickadate/pickadate.css')) }}">


    <link rel="stylesheet" href="{{ asset(mix('vendors/css/editors/quill/quill.snow.css')) }}">
@endsection
@section('content')

    <section id="basic-horizontal-layouts">
        <div class="row match-height d-flex justify-content-center">
            <div class="col-md-6 col-12">
                @if(session('status'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{session('status')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif


                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Detail Transaksi</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                            <div class="form-body">
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Nama Pelanggan</strong></div>
                                    <div class="col-md-8">{{ $data->nama_pelanggan }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Tgl. Reservasi</strong></div>
                                    <div class="col-md-8">{{ $data->created_at }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Nama Bengkel</strong></div>
                                    <div class="col-md-8">{{ $data->bengkel->nama }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Nama Pesanan</strong></div>
                                    @if ($data->jasa)
                                        <div class="col-md-8">Jasa: {{ $data->jasa->nama }}</div>
                                    @else
                                        <div class="col-md-8">Suku Cadang: {{ $data->sukucadang->nama }}</div>
                                    @endif
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Email</strong></div>
                                    <div class="col-md-8">{{ $data->email }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Telepon</strong></div>
                                    <div class="col-md-8">{{ $data->telepon }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Alamat</strong></div>
                                    <div class="col-md-8">{{ $data->alamat }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Tanggal Kedatangan</strong></div>
                                    <div class="col-md-8">{{ $data->tanggal_kedatangan }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Paket</strong></div>
                                    <div class="col-md-8">{{ $data->nama_paket }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Total</strong></div>
                                    <div class="col-md-8">{{ \App\Helpers\Helper::rupiah($data->total) }}</div>
                                </div>
                                <div class="row mb-2">
                                    <div class="col-md-4"><strong>Status Pembayaran</strong></div>
                                    <div class="col-md-8">{{ $data->status_pembayaran  }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    @cannot('isCustomer')
                    <div class="card-footer text-muted">
                        <span class="float-right">
                            <a href="{{ route('transaksi.edit', $data->id) }}" class="btn btn-primary">Edit</a>
                        </span>
                    </div>
                    @endcannot
                </div>

            </div>
    </section>

@endsection

@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.date.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.time.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/legacy.js')) }}"></script>

    <script src="{{ asset(mix('vendors/js/editors/quill/katex.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/highlight.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/quill.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/extensions/jquery.steps.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
@endsection
@section('page-script')
    <!-- Page js files -->
    <script src="{{ asset(mix('js/scripts/forms/select/form-select2.js')) }}"></script>
    <script src="{{ asset(mix('js/scripts/pickers/dateTime/pick-a-datetime.js')) }}"></script>



    <script>
        var editor = new Quill('#snow-container .editor', {
            bounds: '#snow-container .editor',
            modules: {

                toolbar: [
                    ['bold', 'italic', 'underline'],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    ['clean']
                ]
            },
            theme: 'snow'
        });

        var justHtmlContent = document.getElementById('description');

        editor.on('text-change', function() {
            var justHtml = editor.root.innerHTML;
            justHtmlContent.innerHTML = justHtml;
        });
    </script>
@endsection

resources/views/admin/transaksi/form.blade.php
@extends('layouts/admin')

@section('title', 'Transaksi')
@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/pickers/pickadate/pickadate.css')) }}">


    <link rel="stylesheet" href="{{ asset(mix('vendors/css/editors/quill/quill.snow.css')) }}">
@endsection
@section('content')

    <section id="basic-horizontal-layouts">
        <div class="row match-height d-flex justify-content-center">
            <div class="col-md-6 col-12">
                @if(session('status'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{session('status')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                @if ($edit)
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('transaksi.update', $data->id)}}" method="post">
                            @method('PUT')
                @else
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('transaksi.store')}}" method="post">
                @endif
                    @csrf
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ $edit ? 'Edit transaksi' : 'Tambah transaksi' }}</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Status Pembayaran</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <select name="is_paid" class="form-control" id="basicSelect">
                                                        <option value="0" {{ ($edit && $data->is_paid == 0) ? 'selected' : '' }}>Belum Lunas</option>
                                                        <option value="1" {{ ($edit && $data->is_paid == 1) ? 'selected' : '' }}>Lunas</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        <span class="float-left">
                            <button type="reset" class="btn btn-outline-warning">Reset</button>
                        </span>
                        <span class="float-right">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </span>
                    </div>
                </div>
                </form>
            </div>
    </section>

@endsection

@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.date.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.time.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/legacy.js')) }}"></script>

    <script src="{{ asset(mix('vendors/js/editors/quill/katex.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/highlight.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/quill.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/extensions/jquery.steps.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
@endsection
@section('page-script')
    <!-- Page js files -->
    <script src="{{ asset(mix('js/scripts/forms/select/form-select2.js')) }}"></script>
    <script src="{{ asset(mix('js/scripts/pickers/dateTime/pick-a-datetime.js')) }}"></script>



    <script>
        var editor = new Quill('#snow-container .editor', {
            bounds: '#snow-container .editor',
            modules: {

                toolbar: [
                    ['bold', 'italic', 'underline'],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    ['clean']
                ]
            },
            theme: 'snow'
        });

        var justHtmlContent = document.getElementById('description');

        editor.on('text-change', function() {
            var justHtml = editor.root.innerHTML;
            justHtmlContent.innerHTML = justHtml;
        });
    </script>
@endsection

resources/views/admin/transaksi/transaksi.blade.php
@extends('layouts.admin')

@section('title', 'Transaksi')

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header mb-1">
                        <h4 class="card-title">List Transaksi</h4>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                            <div class="table-responsive">
                                <table class="table table-striped zero-configuration">
                                    <thead>
                                    <tr>
                                        <th>Tgl. Reservasi</th>
                                        <th>Nama Pelanggan</th>
                                        <th>Pesanan</th>
                                        <th>Bengkel</th>
                                        <th>Paket</th>
                                        <th>Total</th>
                                        <th>Pembayaran</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($datas as $data)

                                        <tr>
                                            <td>{{ $data->created_at }}</td>
                                            <td>{{ $data->nama_pelanggan }}</td>
                                            @if ($data->jasa)
                                                <td>Jasa: {{ $data->jasa['nama'] }}</td>
                                            @else
                                                <td>Suku Cadang: {{ $data->sukucadang['nama'] }}</td>
                                            @endif

                                            <td>{{ $data->bengkel->nama }}</td>
                                            <td>{{ $data->nama_paket }}</td>
                                            <td>{{ Helper::rupiah($data->total) }}</td>
                                            <td>{{ $data->status_pembayaran }}</td>
                                            <td>
                                                <a href="{{ route('transaksi.show', $data->id) }}" class="btn btn-primary btn-sm">Lihat Detail</a>

                                            </td>
                                        </tr>

                                    @endforeach

                                    </tbody>

                                </table>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
@endsection
@section('page-script')
    {{-- Page js files --}}
    <script src="{{ asset(mix('js/scripts/datatables/datatable.js')) }}"></script>
@endsection