routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/jasa-restorasi', 'HomeController@listJasa')->name('list-jasa');
Route::get('/jasa/{jasa_id}', 'HomeController@detailJasa')->name('detail-jasa');
Route::get('/reservasi-jasa/{jasa_id}', 'HomeController@reservasiJasa')->name('reservasi-jasa');
Route::post('/reservasi-jasa/{jasa_id}', 'HomeController@storeReservasiJasa')->name('reservasi-jasa');

Route::get('/suku-cadang', 'HomeController@listSukuCadang')->name('list-suku-cadang');
Route::get('/suku-cadang/{suku_cadang_id}', 'HomeController@detailSukuCadang')->name('detail-suku-cadang');
Route::get('/booking/{suku_cadang_id}', 'HomeController@bookingSukuCadang')->name('booking-suku-cadang');
Route::post('/booking/{suku_cadang_id}', 'HomeController@storeBookingSukuCadang')->name('booking-suku-cadang');

Route::get('/daftar-keluhan-mobil', 'HomeController@listKeluhan')->name('list-keluhan');
Route::get('/daftar-keluhan-mobil/{keluhan_id}/{slug}', 'HomeController@detailKeluhan')->name('detail-keluhan');

Route::get('/bengkel/{bengkel_id}/{slug}', 'HomeController@detailBengkel')->name('detail-bengkel');
Route::get('/bengkel/', 'HomeController@listBengkel')->name('list-bengkel');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('users', 'UsersController');
    Route::resource('kota', 'KotaController');
    Route::resource('roles', 'RolesController');
    Route::resource('merk', 'MerkController');
    Route::resource('tipe', 'TipeController');
    Route::resource('seri', 'SeriController');
    Route::resource('bengkel', 'BengkelController');
    Route::resource('jasa', 'JasaController');

    Route::get('jasa-harga/{jasa_id}', 'JasaHargaController@create')->name('jasa-harga-form');
    Route::post('jasa-harga/{jasa_id}', 'JasaHargaController@store')->name('jasa-harga-store');
    Route::get('jasa-harga/{jasa_id}/{jasa_harga_id}', 'JasaHargaController@edit')->name('jasa-harga-edit');
    Route::put('jasa-harga/{jasa_id}/{jasa_harga_id}', 'JasaHargaController@update')->name('jasa-harga-update');
    Route::get('jasa-harga-hapus/{jasa_harga_id}', 'JasaHargaController@destroy')->name('jasa-harga-delete');

    Route::resource('suku-cadang', 'SukuCadangController');
    Route::resource('transaksi', 'TransaksiController');
    Route::resource('banner', 'BannerController');
    Route::resource('mekanik', 'MekanikController');
    Route::resource('keluhan', 'KeluhanController');
});

// call with ajax
Route::get('/ajax/get-tipe-by-merk/{merk_id}', 'TipeController@getByMerk')->name('ajax.get-tipe-by-merk');
Route::get('/ajax/get-seri-by-tipe/{tipe_id}', 'SeriController@getByTipe')->name('ajax.get-seri-by-tipe');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

Route::get('/foo', function () {
    Artisan::call('storage:link');
});

app/Models/SukuCadang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SukuCadang extends Model
{
    protected $table = 'suku_cadang';

    public function bengkel()
    {
        return $this->belongsTo(Bengkel::class);
    }

    public function merk()
    {
        return $this->belongsTo(MasterMerk::class);
    }

    public function tipe()
    {
        return $this->belongsTo(MasterTipe::class);
    }

    public function seri()
    {
        return $this->belongsTo(MasterSeri::class);
    }
}

app/Http/Controllers/SukuCadangController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bengkel;
use App\Models\Jasa;
use App\Models\MasterMerk;
use App\Models\MasterSeri;
use App\Models\MasterTipe;
use App\Models\SukuCadang;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SukuCadangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id === 3){
            // cek user ini mempunyai bengkel apa saja
            $bengkelBelongCurrentUser = Bengkel::where('user_id', Auth::user()->id)->pluck('id')->toArray();

            $datas = SukuCadang::whereIn('bengkel_id', $bengkelBelongCurrentUser)->get();
        }else {
            $datas = SukuCadang::all();
        }
        return view('admin.suku-cadang.suku-cadang', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $edit = false;

        if (Auth::user()->role_id === 3){
            $bengkel = Bengkel::where('user_id', Auth::user()->id)->get();
        }else {
            $bengkel = Bengkel::all();
        }

        $merk = MasterMerk::all();
        return view('admin.suku-cadang.form', compact('edit', 'bengkel', 'merk'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new SukuCadang();
        $data->nama = $request->name;
        $data->harga = $request->harga;
        $data->deskripsi = $request->deskripsi;
        $data->bengkel_id = $request->bengkel_id;
        $data->merk_id = $request->merk_id;
        $data->tipe_id = $request->tipe_id;
        $data->seri_id = $request->seri_id;

        if ($request->file('image')) {
            $file = $request->file('image')->store('images', 'public');
            $data->image = $file;
        }

        try{
            $data->save();
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('suku-cadang.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $data = SukuCadang::find($id);

        if (Auth::user()->role_id === 3){
            $bengkel = Bengkel::where('user_id', Auth::user()->id)->get();
        }else {
            $bengkel = Bengkel::all();
        }

        $merk = MasterMerk::all();
        $tipe = MasterTipe::all();
        $seri = MasterSeri::all();
        return view('admin.suku-cadang.form', compact('edit','data', 'bengkel', 'merk', 'tipe', 'seri'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = SukuCadang::find($id);

        $data->nama = $request->name;
        $data->harga = $request->harga;
        $data->deskripsi = $request->deskripsi;
        $data->bengkel_id = $request->bengkel_id;
        $data->merk_id = $request->merk_id;
        $data->tipe_id = $request->tipe_id;
        $data->seri_id = $request->seri_id;

        if ($request->file('image')) {
            $file = $request->file('image')->store('image', 'public');
            $data->image = $file;
        }

        try{
            $data->save();
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('suku-cadang.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            SukuCadang::destroy($id);
        }catch (\Exception $e){
            report($e);
            return redirect()->back()->with('status','Ups, something went wrong. Please try again');
        }

        return redirect()->route('suku-cadang.index');
    }
}

resources/views/admin/suku-cadang/form.blade.php
@extends('layouts/admin')

@section('title', 'Suku Cadang')
@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/pickers/pickadate/pickadate.css')) }}">


    <link rel="stylesheet" href="{{ asset(mix('vendors/css/editors/quill/quill.snow.css')) }}">
@endsection
@section('content')

    <section id="basic-horizontal-layouts">
        <div class="row match-height d-flex justify-content-center">
            <div class="col-md-6 col-12">
                @if(session('status'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{session('status')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                @if ($edit)
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('suku-cadang.update', $data->id)}}" method="post">
                            @method('PUT')
                @else
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('suku-cadang.store')}}" method="post">
                @endif
                    @csrf
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ $edit ? 'Edit Suku Cadang' : 'Tambah Suku Cadang' }}</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Image</span>
                                                </div>
                                                <div class="col-md-8">
                                                    @if ($edit)
                                                        <img src="{{asset('storage/' . $data->image)}}" class="rounded-circle img-border box-shadow-1 mb-2" width="85px" height="85px">
                                                    @endif

                                                    <div class="custom-file">
                                                        <input type="file" class="custom-file-input" name="image" id="image"  required>
                                                        <label class="custom-file-label" for="image"></label>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Nama Suku Cadang</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <input type="text" id="first-name" name="name" class="form-control" value="{{ $edit ? $data->nama : old('name') }}" required>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Deskripsi</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <textarea id="deskripsi" name="deskripsi" class="form-control" required>{{ $edit ? $data->deskripsi : old('deskripsi') }}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Harga</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <input type="number" id="harga" name="harga" class="form-control" value="{{ $edit ? $data->harga : old('harga') }}" required>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Pemilik Bengkel</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <select name="bengkel_id" class="form-control" id="basicSelect">
                                                        @foreach($bengkel as $value)
                                                            <option value="{{ $value->id }}" {{ ($edit && $value->id == $data->bengkel_id) ? 'selected' : '' }}>{{ $value->nama }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Pilih merk</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <select name="merk_id" class="form-control" id="merk">
                                                        @foreach($merk as $value)                                                <option value="{{ $value->id }}" {{ ($edit && $value->id == $data->merk_id) ? 'selected' : '' }}>{{ $value->nama }}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Pilih tipe</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <select name="tipe_id" class="form-control" id="tipe" required>
                                                        @if ($edit)
                                                            @foreach($tipe as $value)
                                                                <option value="{{ $value->id }}" {{ ($edit && $value->id == $data->merk_id) ? 'selected' : '' }}>{{ $value->nama }}</option>
                                                            @endforeach
                                                        @else
                                                            <option value="">-- pilih tipe --</option>
                                                        @endif

                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Seri</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <select name="seri_id" class="form-control" id="seri" required>
                                                        @if ($edit)
                                                            @foreach($seri as $value)
                                                                <option value="{{ $value->id }}" {{ ($edit && $value->id == $data->seri_id) ? 'selected' : '' }}>{{ $value->nama }}</option>
                                                            @endforeach
                                                        @else
                                                            <option value="">-- pilih seri --</option>
                                                        @endif

                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        <span class="float-left">
                            <button type="reset" class="btn btn-outline-warning">Reset</button>
                        </span>
                        <span class="float-right">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </span>
                    </div>
                </div>
                </form>
            </div>
    </section>

@endsection

@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.date.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.time.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/legacy.js')) }}"></script>

    <script src="{{ asset(mix('vendors/js/editors/quill/katex.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/highlight.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/quill.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/extensions/jquery.steps.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
@endsection
@section('page-script')
    <!-- Page js files -->
    <script src="{{ asset(mix('js/scripts/forms/select/form-select2.js')) }}"></script>
    <script src="{{ asset(mix('js/scripts/pickers/dateTime/pick-a-datetime.js')) }}"></script>

    <script>
        $("#merk").on('change', function () {
            var idMerkSelected = $("#merk").val();
            $.ajax({
                type: "GET",
                url: "{{ URL::to('/') }}/ajax/get-tipe-by-merk/" + idMerkSelected,
                success: function (data) {
                    console.log(data)
                    $("#tipe").html(data);
                }
            })
        })

        $("#tipe").on('change', function () {
            var idTipeSelected = $("#tipe").val();
            $.ajax({
                type: "GET",
                url: "{{ URL::to('/') }}/ajax/get-seri-by-tipe/" + idTipeSelected,
                success: function (data) {
                    console.log(data)
                    $("#seri").html(data);
                }
            })
        })
    </script>
@endsection

resources/views/admin/suku-cadang/suku-cadang.blade.php
@extends('layouts.admin')

@section('title', 'Suku Cadang')

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header mb-1">
                        <h4 class="card-title">List Suku Cadang</h4>
                        <a href="{{ route('suku-cadang.create') }}" class="btn btn-primary">Tambah</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                            <div class="table-responsive">
                                <table class="table table-striped zero-configuration">
                                    <thead>
                                    <tr>
                                        <th>Image</th>
                                        <th>Nama Suku Cadang</th>
                                        <th>Harga</th>
                                        <th>Bengkel</th>
                                        <th>Merk</th>
                                        <th>Dibuat pada</th>
                                        <th>Diubah pada</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($datas as $data)

                                        <tr>
                                            <td>
                                                @if ($data->image)
                                                    <div class="avatar mr-1 avatar-lg">
                                                        <img src="{{ asset('storage/image/' . $data->image) }}" alt="" srcset="{{ asset('storage/' . $data->image) }}">
                                                    </div>
                                                @endif
                                            </td>
                                            <td>{{ $data->nama }}</td>
                                            <td>{{ \App\Helpers\Helper::rupiah($data->harga)  }}</td>
                                            <td>{{ $data->bengkel->nama }}</td>
                                            <td>{{ $data->merk->nama }}</td>
                                            <td>{{ $data->created_at }}</td>
                                            <td>{{ $data->updated_at }}</td>
                                            <td>
                                                <a href="{{ route('suku-cadang.edit', $data->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                                <form action="{{ route('suku-cadang.destroy', $data->id) }}" method="POST" class="d-inline">
                                                    @method('DELETE')
                                                    @csrf
                                                    <input type="submit" value="Hapus" class="btn btn-danger btn-sm" onclick="return confirm('Anda yakin akan menghapus data?')">
                                                </form>
                                            </td>
                                        </tr>

                                    @endforeach

                                    </tbody>

                                </table>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
@endsection
@section('page-script')
    {{-- Page js files --}}
    <script src="{{ asset(mix('js/scripts/datatables/datatable.js')) }}"></script>
@endsection