routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/jasa-restorasi', 'HomeController@listJasa')->name('list-jasa');
Route::get('/jasa/{jasa_id}', 'HomeController@detailJasa')->name('detail-jasa');
Route::get('/reservasi-jasa/{jasa_id}', 'HomeController@reservasiJasa')->name('reservasi-jasa');
Route::post('/reservasi-jasa/{jasa_id}', 'HomeController@storeReservasiJasa')->name('reservasi-jasa');

Route::get('/suku-cadang', 'HomeController@listSukuCadang')->name('list-suku-cadang');
Route::get('/suku-cadang/{suku_cadang_id}', 'HomeController@detailSukuCadang')->name('detail-suku-cadang');
Route::get('/booking/{suku_cadang_id}', 'HomeController@bookingSukuCadang')->name('booking-suku-cadang');
Route::post('/booking/{suku_cadang_id}', 'HomeController@storeBookingSukuCadang')->name('booking-suku-cadang');

Route::get('/daftar-keluhan-mobil', 'HomeController@listKeluhan')->name('list-keluhan');
Route::get('/daftar-keluhan-mobil/{keluhan_id}/{slug}', 'HomeController@detailKeluhan')->name('detail-keluhan');

Route::get('/bengkel/{bengkel_id}/{slug}', 'HomeController@detailBengkel')->name('detail-bengkel');
Route::get('/bengkel/', 'HomeController@listBengkel')->name('list-bengkel');

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('users', 'UsersController');
    Route::resource('kota', 'KotaController');
    Route::resource('roles', 'RolesController');
    Route::resource('merk', 'MerkController');
    Route::resource('tipe', 'TipeController');
    Route::resource('seri', 'SeriController');
    Route::resource('bengkel', 'BengkelController');
    Route::resource('jasa', 'JasaController');

    Route::get('jasa-harga/{jasa_id}', 'JasaHargaController@create')->name('jasa-harga-form');
    Route::post('jasa-harga/{jasa_id}', 'JasaHargaController@store')->name('jasa-harga-store');
    Route::get('jasa-harga/{jasa_id}/{jasa_harga_id}', 'JasaHargaController@edit')->name('jasa-harga-edit');
    Route::put('jasa-harga/{jasa_id}/{jasa_harga_id}', 'JasaHargaController@update')->name('jasa-harga-update');
    Route::get('jasa-harga-hapus/{jasa_harga_id}', 'JasaHargaController@destroy')->name('jasa-harga-delete');

    Route::resource('suku-cadang', 'SukuCadangController');
    Route::resource('transaksi', 'TransaksiController');
    Route::resource('banner', 'BannerController');
    Route::resource('mekanik', 'MekanikController');
    Route::resource('keluhan', 'KeluhanController');
});

// call with ajax
Route::get('/ajax/get-tipe-by-merk/{merk_id}', 'TipeController@getByMerk')->name('ajax.get-tipe-by-merk');
Route::get('/ajax/get-seri-by-tipe/{tipe_id}', 'SeriController@getByTipe')->name('ajax.get-seri-by-tipe');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

Route::get('/foo', function () {
    Artisan::call('storage:link');
});

resources/views/admin/mobil-merk/form.blade.php
@extends('layouts/admin')

@section('title', 'Merk')
@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/pickers/pickadate/pickadate.css')) }}">


    <link rel="stylesheet" href="{{ asset(mix('vendors/css/editors/quill/quill.snow.css')) }}">
@endsection
@section('content')

    <section id="basic-horizontal-layouts">
        <div class="row match-height d-flex justify-content-center">
            <div class="col-md-6 col-12">
                @if(session('status'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{session('status')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif

                @if ($edit)
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('merk.update', $data->id)}}" method="post">
                            @method('PUT')
                @else
                        <form enctype="multipart/form-data" class="form form-horizontal" action="{{route('merk.store')}}" method="post">
                @endif
                    @csrf
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ $edit ? 'Edit merk' : 'Tambah merk' }}</h4>
                    </div>
                    <div class="card-content">
                        <div class="card-body">
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Logo</span>
                                                </div>
                                                <div class="col-md-8">
                                                    @if ($edit)
                                                        <img src="{{asset('storage/' . $data->logo)}}" class="rounded-circle img-border box-shadow-1 mb-2" width="85px" height="85px">
                                                    @endif

                                                    <div class="custom-file">
                                                        <input type="file" class="custom-file-input" name="logo" id="avatar"  required>
                                                        <label class="custom-file-label" for="avatar"></label>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-12">
                                            <div class="form-group row">
                                                <div class="col-md-4">
                                                    <span>Name</span>
                                                </div>
                                                <div class="col-md-8">
                                                    <input type="text" id="first-name" name="name" class="form-control" value="{{ $edit ? $data->nama : old('name') }}" required>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        <span class="float-left">
                            <button type="reset" class="btn btn-outline-warning">Reset</button>
                        </span>
                        <span class="float-right">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </span>
                    </div>
                </div>
                </form>
            </div>
    </section>

@endsection

@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.date.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/picker.time.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/pickadate/legacy.js')) }}"></script>

    <script src="{{ asset(mix('vendors/js/editors/quill/katex.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/highlight.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/editors/quill/quill.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/extensions/jquery.steps.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/forms/validation/jquery.validate.min.js')) }}"></script>
@endsection
@section('page-script')
    <!-- Page js files -->
    <script src="{{ asset(mix('js/scripts/forms/select/form-select2.js')) }}"></script>
    <script src="{{ asset(mix('js/scripts/pickers/dateTime/pick-a-datetime.js')) }}"></script>



    <script>
        var editor = new Quill('#snow-container .editor', {
            bounds: '#snow-container .editor',
            modules: {

                toolbar: [
                    ['bold', 'italic', 'underline'],
                    [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                    ['clean']
                ]
            },
            theme: 'snow'
        });

        var justHtmlContent = document.getElementById('description');

        editor.on('text-change', function() {
            var justHtml = editor.root.innerHTML;
            justHtmlContent.innerHTML = justHtml;
        });
    </script>
@endsection

resources/views/admin/mobil-merk/merk.blade.php
@extends('layouts.admin')

@section('title', 'Merk')

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header mb-1">
                        <h4 class="card-title">List Merk</h4>
                        <a href="{{ route('merk.create') }}" class="btn btn-primary">Tambah</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                            <div class="table-responsive">
                                <table class="table table-striped zero-configuration">
                                    <thead>
                                    <tr>
                                        <th>Logo</th>
                                        <th>Nama merk</th>
                                        <th>Dibuat pada</th>
                                        <th>Diubah pada</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($datas as $data)

                                        <tr>
                                            <td>
                                                @if ($data->logo)
                                                    <div class="avatar mr-1 avatar-lg">
                                                        <img src="{{ asset('storage/' . $data->logo) }}" alt="" srcset="{{ asset('storage/' . $data->logo) }}">
                                                    </div>
                                                @endif
                                            </td>
                                            <td>{{ $data->nama }}</td>
                                            <td>{{ $data->created_at }}</td>
                                            <td>{{ $data->updated_at }}</td>
                                            <td>
                                                <a href="{{ route('merk.edit', $data->id) }}" class="btn btn-primary btn-sm">Edit</a>
                                                <form action="{{ route('merk.destroy', $data->id) }}" method="POST" class="d-inline">
                                                    @method('DELETE')
                                                    @csrf
                                                    <input type="submit" value="Hapus" class="btn btn-danger btn-sm" onclick="return confirm('Anda yakin akan menghapus data?')">
                                                </form>
                                            </td>
                                        </tr>

                                    @endforeach

                                    </tbody>

                                </table>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
@endsection
@section('page-script')
    {{-- Page js files --}}
    <script src="{{ asset(mix('js/scripts/datatables/datatable.js')) }}"></script>
@endsection